name: admin_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  core:
    path: ../../core
  cupertino_icons: ^1.0.2
  features:
    path: ../../features
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  package_info_plus: ^1.0.5

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0
  injectable_generator: ^1.5.2
  integration_test:
    sdk: flutter
  mockito: ^5.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: neuzeit
      fonts:
        - asset: assets/fonts/neuzeit.otf
