name: features
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.0
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0
  injectable_generator: ^1.5.2

flutter:
  generate: true
  uses-material-design: true
